sudo: required
language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
services:
  - docker
before_script:
  - chmod a+x ./build.sh
  - chmod a+x ./deploy.sh
script:
  - ./build.sh
deploy:
  - provider: script
    script: ./deploy.sh $DOCKER_USERNAME $DOCKER_PASSWORD
    skip_cleanup: 
    on:
        branch: master