sudo: required
language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
before_install:
- openssl aes-256-cbc -K $encrypted_c390235c8f42_key -iv $encrypted_c390235c8f42_iv
  -in appsettings.json.enc -out appsettings.json -d
install:
- export DOTNET_CLI_TELEMETRY_OPTOUT=1
services:
- docker
before_script:
- chmod a+x ./build.sh
- chmod a+x ./deploy.sh
script:
- "./build.sh"
deploy:
- provider: script
  script: "./deploy.sh $DOCKER_USERNAME $DOCKER_PASSWORD"
  skip_cleanup: 
  on:
    branch: master
