// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog/catalog-service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace prodrink.catalog {

  /// <summary>Holder for reflection information generated from catalog/catalog-service.proto</summary>
  public static partial class CatalogServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for catalog/catalog-service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CatalogServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1jYXRhbG9nL2NhdGFsb2ctc2VydmljZS5wcm90bxIHY2F0YWxvZxoTY2F0",
            "YWxvZy9kcmluay5wcm90bxoRY2F0YWxvZy9kdG8ucHJvdG8yigEKDkNhdGFs",
            "b2dTZXJ2aWNlEjoKDWdldERyaW5rc0J5SWQSFS5jYXRhbG9nLkRyaW5rUmVx",
            "dWVzdBoOLmNhdGFsb2cuRHJpbmsoATABEjwKDWdldERyaW5rc1BhZ2USGS5j",
            "YXRhbG9nLkRyaW5rUGFnZVJlcXVlc3QaDi5jYXRhbG9nLkRyaW5rMAEy8AEK",
            "E0FkbWluQ2F0YWxvZ1NlcnZpY2USPQoLY3JlYXRlRHJpbmsSDi5jYXRhbG9n",
            "LkRyaW5rGh4uY2F0YWxvZy5Ecmlua0NyZWF0aW9uUmVzcG9uc2USSAoLdXBk",
            "YXRlRHJpbmsSGy5jYXRhbG9nLkRyaW5rVXBkYXRlUmVxdWVzdBocLmNhdGFs",
            "b2cuRHJpbmtVcGRhdGVSZXNwb25zZRJQCgtkZWxldGVEcmluaxIdLmNhdGFs",
            "b2cuRHJpbmtEZWxldGlvblJlcXVlc3QaHi5jYXRhbG9nLkRyaW5rRGVsZXRp",
            "b25SZXNwb25zZSgBMAFCRwobaW8ucHJvZHJpbmsuY2F0YWxvZy5zZXJ2aWNl",
            "QhNDYXRhbG9nU2VydmljZU91dGVyUAGqAhBwcm9kcmluay5jYXRhbG9nYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::prodrink.catalog.DrinkReflection.Descriptor, global::prodrink.catalog.DtoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
